---
title: "Final project"
author: "Marina Blum"
date: "12/6/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("C:\\Users\\Blum\\Desktop")
library(vroom)
library(censusapi)
library(tidycensus)
library(tidyverse)
library(data.table)
library(plyr)
```


```{r sfdata}
sfdata <- vroom("COVID-19_Cases_by_Geography_and_Date.csv")
str(sfdata)
head(sfdata)
sfdata <- sfdata[, 1:8]
unique(sfdata$area_type)
sfdata$area_type <- sfdata$area_type[, area_type == "ZCTA"]
unique(sfdata$`Specimen Collection Date`)

newdata <- sfdata[which(sfdata$area_type=="ZCTA" & sfdata$`Specimen Collection Date`=="2020-12-03"),]
head(newdata)
finaldata <- newdata[, c("id", "acs_population", "Cumulative Confirmed Cases", "Rate of Cumulative Confirmed Case")]
write.csv(finaldata, file = "C:/Users/Blum/Desktop/sfdata.csv")
as.data.frame(finaldata)
```

```{r census key}
# Add key to .Renviron
census_api_key("5e8cf3dd21e78fa611d78909ac557c6580b30546", overwrite = TRUE, install = TRUE)
# Reload .Renviron
readRenviron("~/.Renviron")
# Check to see that the expected key is output in your R console
Sys.getenv("CENSUS_KEY")
```

```{r acs}

#Census variable names for reference
v17 <- load_variables(2010, "acs5", cache = TRUE)
View(v17)

## Part 1: find median income for black and white population in Dallas County, 2010
#data pull
dallas <- get_acs(state = "TX", 
              county = "Dallas",
              geography = "tract",
              year = 2010,
              variables = c(median_inc_b = "B19113B_001", median_inc_w = "B19113A_001"),
              survey = "acs5")

#restructure data; 
dallas2 <- dallas %>% select(1:4)
dallas_wider <- dallas2 %>% pivot_wider(
                  names_from = variable,
                  values_from = estimate
)

median_w <- median(dallas_wider$median_inc_w, na.rm = TRUE)
median_b <- median(dallas_wider$median_inc_b, na.rm = TRUE)

#difference between black and white median income
diff_median <- median_w - median_b 

#### Pt. 2 visualize results spatially

#get black median income by census tract
map_dallas <- get_acs(state = "TX", 
              county = "Dallas",
              geography = "tract",
              year = 2010,
              geometry = TRUE,
              variables = c(median_inc_b = "B19113B_001"),
              survey = "acs5")

head(map_dallas)

#calculate coefficient of variation, reliability cutoff at 40% variation based on moe
map_dallas %>% mutate(cov = (moe/1.645)/estimate, reliable = ifelse(cov > 0.40, 1, 0))

#visualize black median incomes by census tract
map_dallas %>% 
  ggplot(aes(fill = estimate)) +
  geom_sf(color = NA) +
  coord_sf(crs = 26911) +
  scale_fill_viridis_c(option = "magma") +
  theme_minimal() +
    labs(title = str_wrap("Median Income among Black Residents by Census Tract Dallas County, 2010", 55), fill = "Median Income ($)") +
  theme(plot.title = element_text(hjust = 0.5))

#visualize white median income by census tract, calc cov, visualize
wmap_dallas <- get_acs(state = "TX", 
              county = "Dallas",
              geography = "tract",
              year = 2010,
              geometry = TRUE,
              variables = c(median_inc_w = "B19113A_001"),
              survey = "acs5")

wmap_dallas2 <- wmap_dallas %>% mutate(cov = (moe/1.645)/estimate, reliable = ifelse(cov > 0.40, 1, 0))
alpha <- ifelse(wmap_dallas2$reliable, 0, 0.1)

#map w/o moe
wmap_dallas %>% 
  ggplot(aes(fill = estimate)) +
  geom_sf(color = NA) +
  coord_sf(crs = 26911) +
  scale_fill_viridis_c(option = "magma") +
  theme_minimal() +
  labs(title = str_wrap("Median Income among White Residents by Census Tract Dallas County, 2010", 55), fill = "Median Income ($)") +
  theme(plot.title = element_text(hjust = 0.5)) 

#map w/O moe and reliabilty exclusions

wmap_dallas2 %>% 
  ggplot(aes(fill = estimate, alpha = alpha)) +
  geom_sf(color = NA) +
  coord_sf(crs = 26911) +
  scale_fill_viridis_c(option = "magma") +
    scale_alpha_continuous(guide = FALSE) +
  theme_minimal() +
  labs(title = str_wrap("Median Income among White Residents by Census Tract Dallas County, 2010", 55), fill = "Median Income ($)", caption = "*White fill is low reliability data, while grey fill indicates no data available.") +
  theme(plot.title = element_text(hjust = 0.5))

```

```{r}
#market rate data - IN PROGRESS - 
map_dallas <- get_acs(state = "NY", 
              county = "Dallas",
              geography = "tract",
              year = 2010,
              geometry = TRUE,
              variables = c(median_inc_b = "B19113B_001"),
              survey = "acs5")

#community districts 2 and 7. PUMA # 0400(0)4. HVS HOUSING VACANCY SURVEY CENSUS + NYC. 1993. 96 98/9

```

